[profiles.sublime.dots.sublime-keymap]
source = "configs/sublime/Default (OSX).sublime-keymap"
target = "Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap"


[profiles.sublime.dots.sublime-packages]
source = "configs/sublime/Package Control.sublime-settings"
target = "Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings"


[profiles.sublime.dots.sublime-prefs]
source = "configs/sublime/Preferences.sublime-settings"
target = "Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"

