dotfiles_dir = ".dotfiles"

[settings]
vars = ["vars.toml"]

[profiles.all]
extra_profiles = ["fish", "helix", "sublime"]


[[import]]
path = "configs/fish/config.toml"

[[import]]
path = "configs/helix/config.toml"

[[import]]
path = "configs/sublime/config.toml"
