# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = ".dotfiles"

[settings]
# An array of toml files paths containing the variables to inject in your templatized dotfiles
# You can have multiple var files as long as variable names does not colide.
# vars = [ "vars.toml" ]

# An array of post install shell commands
# posthooks = [ "sway reload" ]

[settings.dots]

# A dot entry representing a symlink, `source` is relative to `dotfiles_dir`
# and `target` shall be relative to $HOME directory or absolute.
sway = { source = "sway", target = ".config/sway" }

# You can have as many dot entry as you want, linking files or directories
# alacritty = { source = "alacritty.yml", target = ".config/alacritty/alacritty.yml" }


fish = {source = "fish-config.fish", target = ".config/fish/config.fish"}
helix = {source = "helix-config.toml", target = ".config/helix/config.toml"}
