# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = ".dotfiles"

[settings.dots]

fish = { source = "fish-config.fish", target = ".config/fish/config.fish" }
helix = { source = "helix-config.toml", target = ".config/helix/config.toml" }
